@startuml Hover-diagrama_de_flujo

<style>
activityDiagram {
    FontName arial
}
</style>

:Splines y cálculos preliminares]
floating note left: Hover-input.csv

start
partition 1º #LightSkyBlue {
    repeat
        :\t\t     **1º Ciclo:**\nRecorrido de ángulos colectivos;
        if (θ < Nθ) then (Si)
            partition 2º #LightBlue {
                repeat
                    :\t\t**2º Ciclo:**\nRecorrido de estaciones;
                    if (xi < Nx) then (Si)
                        partition 3º #LightGrey {
                            :  **3º Ciclo:**\nIteraciones;
                                while (error > Tol) is (Si)
                                    if (Iteracion max) then (Si)
                                        break
                                    else (No)
                                        :Nueva iteración;
                                    endif
                                    if (Solucion compleja) then (Si)
                                        break
                                    else (No)
                                        endif
                                endwhile (No)
                            :Impresión en **.txt**;
                        }
                    else (No)
                        :Fin de **2º Ciclo**;
                        :Impresión en **.txt**;
                    endif
                backward:Próxima estación xi;
                repeat while (Fin de **2º Ciclo**) is (No) not (Si)
            }
        else (No)
            :Fin de **1º Ciclo**;
            :Impresión en **.txt**;
        endif
    backward :Próximo ángulo θ;
    repeat while (Fin de **1º Ciclo**) is (No) not (Si)
}
:Exportación en **.txt**;
end

@endump